from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal, Sequence
import os


### 
#  plan to handle all imports in jupyter notebook, then
# into workflow? 
# pip install biopython
# %pip install "colabfold[alphafold]" "jax[cuda12]"




## ADD ALL IMPORTS FOR PROJECT HERE? 

## make sure to remove them from the computer afterwards. this software
## is a little invasive on peoples folders as of now.


DEFAULT_ESM2_MODEL = 'facebook/esm2_t33_650M_UR50D'

## Need to figure out what these are doing a little better. i think this is on my actual hard drive. 
def _default_eup_repo() -> Path:
    if Path('/content').exists():
        return Path('/content/external/EUP')
    return Path.home() / '.cache' / 'therapeutic_optimization' / 'ESM'

def _default_hf_cache() -> Path:
    if Path('/content').exists():
        return Path('/content/huggingface')
    return Path.home() / '.cache' / 'huggingface'

@dataclass(slots=True)
class T2Config:
    """Hyperparameters controlling T2 mutation site list."""
    threshold: float = 0.40

### assert that the amino acids we are replacing with are valid



# TO DO : structural threshold configuration (currently chatted) 
@dataclass(slots=True)
class StructuralThresholds:
    """
    Transparent, user-adjustable heuristic gates for S1.

    These are workflow defaults, not universal biological cutoffs.
    """
    ## TO DO: fill in 
    global_ca_rmsd_max: float = 1.0
    binder_start: int | None = None
    binder_end: int | None = None
    binder_ca_rmsd_max: float = 1.0
    core_ca_rmsd_max: float = 1.0
    local_mean_ca_displacement_max: float = 1.5
    mutation_ca_displacement_max: float = 2.0
    contact_change_fraction_max: float = 0.10
    min_mean_plddt: float = 70.0

    def binder_positions(self) -> tuple[int, int] | None:
        """Return the inclusive binder range, or None when domain-aware analysis is disabled."""
        if self.binder_start is None and self.binder_end is None:
            return None
        if self.binder_start is None or self.binder_end is None:
            raise ValueError('binder_start and binder_end must be set together.')
        if self.binder_start < 1 or self.binder_end < self.binder_start:
            raise ValueError('Binder positions must define a positive, inclusive residue range.')
        return self.binder_start, self.binder_end



### TODO: generated by AI, am planning to preserve.
@dataclass(slots=True)
class ESM2AnalysisConfig:
    """Runtime and ranking choices for WT-versus-mutant ESM-2 analysis.

    The default 650M model is practical on common Colab GPUs. The larger
    ``facebook/esm2_t36_3B_UR50D`` model can be selected when memory permits.
    """

    model_name: str = DEFAULT_ESM2_MODEL
    mask_batch_size: int = 4
    device: str | None = None
    dtype: Literal['auto', 'float32', 'float16', 'bfloat16'] = 'auto'
    model_cache_dir: str | Path | None = field(default_factory=_default_hf_cache)
    save_per_residue: bool = True
    fail_fast: bool = False
    perplexity_weight: float = 0.70
    representation_weight: float = 0.30

    def validate(self) -> None:
        if not self.model_name.strip():
            raise ValueError('ESM-2 model_name cannot be empty.')
        if self.mask_batch_size < 1:
            raise ValueError('ESM-2 mask_batch_size must be at least 1.')
        if self.dtype not in {'auto', 'float32', 'float16', 'bfloat16'}:
            raise ValueError(f'Unsupported ESM-2 dtype: {self.dtype!r}.')
        if self.perplexity_weight < 0 or self.representation_weight < 0:
            raise ValueError('ESM-2 scoring weights cannot be negative.')
        if self.perplexity_weight + self.representation_weight <= 0:
            raise ValueError('ESM-2 requires at least one positive scoring weight.')



@dataclass(slots=True)
class ProjectPaths:
    root: Path
    stage_suffix: str = ''

#TODO: not sure about this
    @classmethod
    def from_root(cls, root: str | Path, stage_suffix: str = '') -> 'ProjectPaths':
        return cls(Path(root).expanduser().resolve(), stage_suffix)
##^^


## this sets the folder pathways up.

    @property
    def storage(self) -> Path:
        return self.root / 'storage'

    @property
    def input(self) -> Path:
        return self.storage / 'input'

    @property
    def mutants(self) -> Path:
        return self.storage / 'fastas'

    @property
    def models(self) -> Path:
        return self.storage / 'models'

    @property
    def property_predictors(self) -> Path:
        return self.storage.models / 'property_predictors'

    @property
    def ESM2(self) -> Path:
        return self.storage.models / 'ESM2'

    @property
    def AlphaFold(self) -> Path:
        return self.storage.models / 'AlphaFold'

    @property
    def colabFold(self) -> Path:
        return self.storage.models / 'colabFold'

    @property
    def ignore(self) -> Path:
        return self.storage / 'ignore'

    @property
    def results(self) -> Path:
        return self.storage / 'results'

    def ensure(self) -> None:
        for path in (
            self.storage,
            self.input,
            self.mutants,
            self.models,
            self.property_predictors,
            self.ESM2,
            self.AlphaFold,
            self.colabFold,
            self.ingnore,
            self.results
        ):
            path.mkdir(parents=True, exist_ok=True)

